sudo: required
dist: bionic
language: cpp
matrix:
  include:
  - os: linux
    env: TARGET=linux_x86_64
  - os: linux
    env: TARGET=linux_i686
  - os: linux
    env: TARGET=linux_armv7l
  - os: linux
    env: TARGET=linux_aarch64
  - os: linux
    env: TARGET=windows_x86
  - os: linux
    env: TARGET=windows_amd64
  - os: osx
    env: TARGET=darwin
before_script:
- if [[ ${TARGET:0:7} == "windows" ]]; then sudo dpkg --add-architecture i386; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y -qq; fi
script:
- bash build.sh $TARGET
- openssl sha1 _packages/**/*.tar.gz
deploy:
  provider: releases
  api_key:
    secure: 1opHR+xAD/YbtggpTADlXCGRJoNfH2s/kt/4Ytki9GBqo/Bvjlt7Yz/k2k3rt8waXXHjm4Tek5uT9elmi5fRiXoryhishti2jkF0WDoDX0ADyNlGT213I83DCCSnsM9VxcLi0I5GeUNJvaPNTeUdZoUyrxWNYbwpLmZihCGPDDfqzD+XmmbNHWfq3JaRlXaPVme6YYyWEZOUOfAZSryRNxBbIwdl0kGor0BL8jmR+U6skpi9Zbv5e0gUx103Jv3eeHrxmrG7XlRMcd5LpYyI+irnKAemzZUSYi4QcSwwNBZkLR/uCivDHnFKiFtrEHO4/KxOKkfoqZutdEynIOANKGuffqcAvTV7sVBTLZD1Ooe2CC/TXqnoXmaJgjJYcY44nVZCcg7cUBXoG2rULH+/lhCG4ucPrbH/PtGWbrmuudrttV//sjQ3+1MFHIcFYOVEM0Eza/uvi7AWNF11YA6Awu9MWh4mMgqWpeUdi4vsZFJeSe2gUPgscx2AhI6EOZn2MYgM6cJesjVtYfN0AnsWwOoqabLxzKeoVSJ4xM3IGWdCVzVC1vbDFBG2UFy32GpX0QfTLwN8tqpCnZHNXF+MiJ+/6a79V/POb3Mlm9ybcMN/b6RD/cq2fm56Q8RGMZolM/5OvHfymtXPa+34QMZUrHCy3viZIG4kk3DYGe2PC3A=
  file: _packages/**/*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: elutow/toolchain-verilator
    tag: true
